name = "itmraudio-site"
pages_build_output_dir = "."
compatibility_date = "2026-10-06"

[[d1_databases]]
binding = "SIGNUPS"
database_name = "itmraudio-signups"
database_id = "66148a75-e3a1-4e75-ac17-110474c7c05b"
