"""Generate static crawler metadata. No JavaScript is required to read it."""
from pathlib import Path
import json
import re
from html import escape

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://itmraudio.com"
BRAND = "ITMR Audio"
DESCRIPTION = "ITMR Audio develops audio plugins for independent artists and producers, including ARC VOX vocal processing and ARC FX creative multi-effects."
PAGES = [
    dict(file="index.html", path="/", title="ITMR Audio | Vocal & Creative Effects Plugins",
         description="Meet ITMR Audio's plugins for independent artists: ARC VOX for vocal processing and ARC FX for creative effects. Explore the tools and join early access.",
         image="itmr-audio-plugins", image_alt="ITMR Audio audio plugins: ARC VOX vocal processing and ARC FX creative multi-effects.", name=BRAND),
    dict(file="arc-vox.html", path="/arc-vox", title="ARC VOX Vocal Processing Plugin | ITMR Audio",
         description="Explore ARC VOX by ITMR Audio: a vocal plugin with cleanup, pitch correction, de-essing, compression, six-band EQ, color and space. Early access coming soon.",
         image="arc-vox-vocal-plugin", image_alt="ARC VOX by ITMR Audio: the vocal plugin's Voice screen with CONTROL and CHARACTER knobs.", name="ARC VOX",
         features=["Learn Voice", "Vocal cleanup", "Pitch correction", "De-essing", "Vocal compression", "Six-band parametric EQ", "Harmonic color", "Reverb and delay"], category="Vocal processing plugin",
         screenshot="assets/vox/01-voice.webp"),
    dict(file="arc-fx.html", path="/arc-fx", title="ARC FX Creative Multi-Effects Plugin | ITMR Audio",
         description="Explore ARC FX by ITMR Audio: 17 creative effects, a reorderable pedal rack, and FLUX and ROAM controls for sound design. Join the early-access list.",
         image="arc-fx-effects-plugin", image_alt="ARC FX by ITMR Audio: the Create screen with FLUX and ROAM macro controls and its effects generator.", name="ARC FX",
         features=["17 creative effects", "Up to 12 rack slots", "Reorderable effects", "Serial, parallel and mid/side routing", "FLUX transformation amount", "ROAM movement control"], category="Creative multi-effects plugin",
         screenshot="assets/fx/scr/01-create-flux-roam-2x.png"),
]


def organization():
    # Add sameAs only when official brand accounts actually exist.
    return {"@type": "Organization", "@id": BASE + "/#organization", "name": BRAND,
            "alternateName": "itmraudio.com", "url": BASE + "/", "description": DESCRIPTION,
            "logo": {"@type": "ImageObject", "url": BASE + "/assets/brand/itmr-audio-icon-512.png", "width": 512, "height": 512}}


def graph(page):
    url = BASE + page["path"]
    org = organization()
    webpage = {"@type": "WebPage", "@id": url + "#webpage", "url": url,
               "name": page["title"], "description": page["description"], "inLanguage": "en",
               "isPartOf": {"@id": BASE + "/#website"}, "publisher": {"@id": org["@id"]}}
    website = {"@type": "WebSite", "@id": BASE + "/#website", "url": BASE + "/",
               "name": BRAND, "alternateName": "itmraudio.com", "publisher": {"@id": org["@id"]}}
    nodes = [org, website, webpage]
    if page["path"] == "/":
        webpage["about"] = {"@id": org["@id"]}
        webpage["mainEntity"] = {"@type": "ItemList", "itemListElement": [
            {"@type": "ListItem", "position": i, "name": p["name"], "url": BASE + p["path"]}
            for i, p in enumerate(PAGES[1:], 1)]}
    else:
        app_id = url + "#software"
        webpage["mainEntity"] = {"@id": app_id}
        webpage["breadcrumb"] = {"@id": url + "#breadcrumb"}
        # Descriptive software data only: no invented reviews, prices or release dates.
        nodes += [{"@type": "SoftwareApplication", "@id": app_id, "name": page["name"],
                   "url": url, "description": page["description"], "applicationCategory": "MultimediaApplication",
                   "applicationSubCategory": page["category"], "featureList": page["features"],
                   "screenshot": BASE + "/" + page["screenshot"], "creator": {"@id": org["@id"]},
                   "publisher": {"@id": org["@id"]}},
                  {"@type": "BreadcrumbList", "@id": url + "#breadcrumb", "itemListElement": [
                      {"@type": "ListItem", "position": 1, "name": BRAND, "item": BASE + "/"},
                      {"@type": "ListItem", "position": 2, "name": page["name"], "item": url}]}]
    return {"@context": "https://schema.org", "@graph": nodes}


def metadata(page):
    title, desc = escape(page["title"], quote=True), escape(page["description"], quote=True)
    url, img = BASE + page["path"], BASE + "/assets/social/" + page["image"] + ".png"
    alt = escape(page["image_alt"], quote=True)
    return f'''<!-- SEO:START — generated by tools/build_seo.py -->
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{url}">
<meta name="robots" content="index, follow, max-image-preview:large">
<meta name="theme-color" content="#0c0e0b">
<meta property="og:type" content="website">
<meta property="og:site_name" content="{BRAND}">
<meta property="og:locale" content="en_US">
<meta property="og:url" content="{url}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="{img}">
<meta property="og:image:secure_url" content="{img}">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{alt}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="{img}">
<meta name="twitter:image:alt" content="{alt}">
<link rel="icon" type="image/svg+xml" href="/assets/brand/itmr-audio-symbol-signal.svg">
<link rel="icon" type="image/png" sizes="96x96" href="/assets/brand/itmr-audio-icon-96.png">
<link rel="apple-touch-icon" sizes="180x180" href="/assets/brand/itmr-audio-icon-180.png">
<script type="application/ld+json">
{json.dumps(graph(page), ensure_ascii=False, indent=2)}
</script>
<!-- SEO:END -->'''


def main():
    for page in PAGES:
        path = ROOT / page["file"]
        html = path.read_text(encoding="utf-8")
        if "<!-- SEO:START" in html:
            html = re.sub(r"<!-- SEO:START.*?<!-- SEO:END -->", metadata(page), html, count=1, flags=re.S)
        else:
            html = re.sub(r'<title>.*?</title>\s*', '', html, count=1)
            html = re.sub(r'<meta name="description"[^>]*>\s*', '', html, count=1)
            html = re.sub(r'<link rel="icon"[^>]*>\s*', '', html)
            html = html.replace('<link rel="preconnect"', metadata(page) + '\n<link rel="preconnect"', 1)
        path.write_text(html, encoding="utf-8", newline="\n")
    # lastmod is deliberately omitted rather than claiming a content edit every build.
    urls = '\n'.join(f'  <url><loc>{BASE}{p["path"]}</loc></url>' for p in PAGES)
    (ROOT / "sitemap.xml").write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + urls + '\n</urlset>\n', encoding="utf-8")
    print("Built static metadata and sitemap for 3 pages.")


if __name__ == "__main__":
    main()
